version: '2'
services:
  app1:
    build: .
    image: malev/corenlp
    hostname: app1
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    restart: always
  app2:
    build: .
    image: malev/corenlp
    hostname: app2
    ports:
      - 3002:3002
    environment:
      PORT: 3002
    restart: always
  app3:
    build: .
    image: malev/corenlp
    hostname: app3
    ports:
      - 3003:3003
    environment:
      PORT: 3003
    restart: always
  app4:
    build: .
    image: malev/corenlp
    hostname: app4
    ports:
      - 3004:3004
    environment:
      PORT: 3004
    restart: always

  loadbalancer:
      image: nginx
      ports:
          - 8080:80
      volumes:
          - ./corenlp.conf:/etc/nginx/conf.d/default.conf:ro
  cadvisor:
    image: google/cadvisor
    ports:
      - 8000:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
