Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install wget vim build-essential -yq
    wget https://s3-us-west-2.amazonaws.com/data.codingnews.info/jre-8u91-linux-x64.tar.gz
    tar xvzf jre-8u91-linux-x64.tar.gz
    mv jre1.8.0_91 /usr/java
    ln -s /usr/java/bin/java /usr/bin/java

    curl -sL https://deb.nodesource.com/setup_4.x -o nodesource_setup.sh
    bash nodesource_setup.sh
    sudo apt-get install default-jdk -yq
  SHELL
end
