Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install wget vim build-essential -yq

    echo "java 8 installation"
    apt-get install --yes python-software-properties
    add-apt-repository ppa:webupd8team/java
    apt-get update -qq
    echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
    apt-get install --yes oracle-java8-installer
    yes "" | apt-get -f install

    echo "Node.js 4.x installation"
    curl -sL https://deb.nodesource.com/setup_4.x -o nodesource_setup.sh
    bash nodesource_setup.sh
    sudo apt-get install nodejs -yq
  SHELL
end
